#:schema node_modules/wrangler/config-schema.json
name = "workers-assets-test-svelte"
compatibility_date = "2024-08-21"

main = ".svelte-kit/cloudflare/_worker.js"
experimental_assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }
